get remote resource only after all cache failed
tldr-pages/tldr-python-client pull request #151
Opened 2021-01-04 09:48 UTC by ramwin

2021-01-04 13:38 UTC, MasterOdin requested changes
Thanks for the PR. I've made some review comments to resolve, and then I think we can merge this.

2021-01-04 13:38 UTC, MasterOdin commented on tldr.py
> +                    command, platform, remote, language, only_use_cache=True)
```suggestion
                return get_page_for_platform(
                    command,
                    platform,
                    remote,
                    language,
                    only_use_cache=True,
                )
```

2021-01-04 13:38 UTC, MasterOdin commented on tldr.py
> +                ))
```suggestion
            raise CacheNotExist("Cache for {} in {} not Found".format(
                command,
                platform,
            ))
```

2021-01-04 13:38 UTC, MasterOdin commented on tldr.py
> +    for platform in platforms:
Let's wrap a `if USE_CACHE:` around this so as to avoid wasted cycles on entering the function and exception handling if we don't need it.

2021-01-04 13:38 UTC, MasterOdin commented on tldr.py
> +        if only_use_cache:
We can combine these to a single statement:

```suggestion
    elif only_use_cache:
```

2021-01-04 14:42 UTC, ramwin commented
Thank you for your advises, I accept all of them.

2021-01-05 01:59 UTC, ramwin reviewed
Thank you for your advises, I accept all of them.

2021-01-31 03:34 UTC, bl-ue commented
@MasterOdin will you please review this again?  Thank you.

2021-02-01 01:53 UTC, MasterOdin approved these changes

2021-02-01 01:54 UTC, merged