Change TLDR_CACHE_MAX_AGE default
tldr-pages/tldr-python-client pull request #170
Opened 2021-11-07 00:55 UTC by CleanMachine1

I feel 24 hours is extreme, and it annoys me when I first started using this client.

On average I probably only use tldr 1-2 times a day, therefore I have to wait each time for it to download a new cache everyday, which normally includes the additions of 0-10 pages/changes.

It goes from nearly instant with using an _out of date cache_ to waiting a few seconds for a command if you use an __updated cache__ 

Simple change, however others may find this controversial :shrug:

2021-11-07 00:59 UTC, CleanMachine1 commented
Do I need to remove the comments?

2021-11-07 12:22 UTC, marchersimon approved these changes
I agree with the changes, but I think the added comments are not really necessary. Either way, thanks

2021-11-07 12:25 UTC, sbrl approved these changes
Thanks, @CleanMachine1!

Looking at the commit history let's wait for @MasterOdin to merge this?

2021-11-07 12:25 UTC, sbrl commented
Hrm, some of the builds are failing here?

2021-11-07 12:37 UTC, marchersimon commented
> ./tldr.py:33:67: E261 at least two spaces before inline comment
./tldr.py:34:63: E261 at least two spaces before inline comment
./tldr.py:35:63: E261 at least two spaces before inline comment
./tldr.py:35:89: E501 line too long (95 > 88 characters)

Those are all because of the comments. As already said, I don't think they're necessary.

2021-11-07 17:24 UTC, owenvoke approved these changes

2021-11-08 20:44 UTC, CleanMachine1 commented
@MasterOdin Could we get a review?

2021-11-10 20:46 UTC, MasterOdin requested changes

2021-11-10 20:46 UTC, MasterOdin commented on README.md
> +* `TLDR_CACHE_MAX_AGE` (default is `168`): maximum age of the cache in hours to be considered as valid when `TLDR_CACHE_ENABLED` is set to `1`.
Can we specify what `168` is here?

> (default is `168` hours, or one week)

2021-11-10 20:46 UTC, MasterOdin commented on tldr.py
> +MAX_CACHE_AGE = int(os.environ.get('TLDR_CACHE_MAX_AGE', 168))
Can you change this to be `24 * 7`? Makes it a bit easier to quickly parse.

2021-11-12 12:40 UTC, CleanMachine1 commented
Can I get some reviews here please

2021-11-12 13:57 UTC, marchersimon approved these changes

2021-11-12 23:49 UTC, merged