Notice other versions of the same page
tldr-pages/tldr-python-client pull request #208
Opened 2023-01-25 20:18 UTC by Jaimepas77

Fixes #193 

This PR changes the way pages are searched so that it can find multiple versions of the same page. Therefore, every time a page is searched, every possible platform is checked even if a previous valid one was found. If more than one page is found, the next platform in the priority list is noticed to the user.

It doesn't search in every page if the platform was determined by the user parameters.

The PR implements this [specification](https://github.com/tldr-pages/tldr/blob/main/CLIENT-SPECIFICATION.md#if-multiple-versions-of-a-page-were-found).

Bugs: it wont find multiple versions of the page if the cache only contains one of them. As it's much faster to search on the cache, this bug was not resolved.

2023-02-07 19:30 UTC, CleanMachine1 commented on tldr.py
> +                    print(f"There are other versions of this page in the {platform_str} category.")
```suggestion
                    print(f"There are other versions of this page under the {platform_str} platform.")
```

2024-01-30 16:21 UTC, vitorhcl requested changes

2024-01-30 16:21 UTC, vitorhcl commented on tldr.py
> +                    print("There are other versions of this page under the {} platform.".format(platform_str))
```suggestion
                    platforms_str = [result[1] for result in results[1:]]
                    single = len(platforms_str) == 1
                    print(f"There {'is' if single else 'are'} other version{'' if single else 's'} of this page under the following platform{'' if single else 's'}: {', '.join(platforms_str)}.")
```

2024-02-23 12:10 UTC, vitorhcl commented
I ran black on the script

2024-02-23 13:56 UTC, vitorhcl commented
I reverted black formatting to not conflict with other PRs for now. We can maybe run it in another PR

2024-06-05 10:10 UTC, kbdharun approved these changes

2024-06-05 20:00 UTC, vitorhcl reviewed
LGTM after some minor changes

2024-06-06 05:14 UTC, kbdharun approved these changes

2024-06-06 12:31 UTC, vitorhcl approved these changes
LGTM, thank you @kbdharun and @Jaimepas77!

2024-06-06 13:34 UTC, merged