fix: return `str` instead of `list` when executing `tldr -l`
tldr-pages/tldr-python-client pull request #222
Opened 2023-10-29 06:25 UTC by uunnxx

Return `str` separated by `\n`.

It helps when using by other programs, like `fzf`
I've `alias`:
`alias ch="tldr \$(tldr -l | fzf)"`
so it'll search through all pages.

![focused_window_2023-10-29_09-24-04_900x450](https://github.com/tldr-pages/tldr-python-client/assets/6236057/f72c4bd4-8c3e-47e6-a1f1-b16c040196e7)

2023-11-18 17:27 UTC, acuteenvy requested changes
This breaks the `--search` option. All you need to do to output the list as a newline-separated string is to change
```python
print(get_commands(options.platform))
````
to
```python
print('\n'.join(get_commands(options.platform)))
```
on [line 507](https://github.com/tldr-pages/tldr-python-client/blob/15242e81e833f89a28a605cfb04ffed6a32af20c/tldr.py#L507).

2024-01-17 01:19 UTC, vitorhcl commented
@kbdharun @acuteenvy as this is a minor change, I think you can apply @acuteenvy's suggestion and merge this

2024-01-18 13:15 UTC, acuteenvy approved these changes

2024-01-21 04:35 UTC, vitorhcl approved these changes

2024-01-21 07:16 UTC, kbdharun approved these changes
LGTM, Thanks for your contribution.

2024-01-21 07:17 UTC, merged