refactor: use pathlib instead of os.path
tldr-pages/tldr-python-client pull request #224
Opened 2024-01-13 02:29 UTC by vitorhcl

pathlib provides a much cleaner spearation between strings and paths, leaves "/" operator for joining paths and also provides some builtin methods, improving the code readabilty and mantainability.

2024-01-15 21:36 UTC, JacobCallahan requested changes
love pathlib!

2024-01-15 21:36 UTC, JacobCallahan commented on tldr.py
> +            if Path(command).exists:
This is a method call
```suggestion
            if Path(command).exists():
```

2024-01-16 14:03 UTC, kbdharun approved these changes

2024-01-16 14:05 UTC, kbdharun commented
Interestingly, this is failing CI for older versions of Python.

2024-02-18 12:21 UTC, vitorhcl commented on tests/test_tldr.py
>      monkeypatch.setattr(os.path, 'expanduser', lambda _: '/tmp/expanduser')
```suggestion
     monkeypatch.setattr(pathlib.Path, 'home', lambda _: '/tmp/expanduser')
```

2024-02-23 11:42 UTC, owenvoke approved these changes

2024-02-24 15:54 UTC, merged